# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.1
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: apidb
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipass
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:4.0.3
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=test1
      - AWS_SECRET_ACCESS_KEY=test2
      - DEBUG=1
      - S3_SKIP_SIGNATURE_VALIDATION=0
    volumes:
      - localstack_data:/var/lib/localstack
      - ./docker/localstack/init:/etc/localstack/init

volumes:
  localstack_data:
